# Configuraci�n de la base de datos (SQL Server)
spring.datasource.url=jdbc:sqlserver://serverpdb.database.windows.net:1433;databaseName=erpdb;encrypt=true;trustServerCertificate=false;authentication=ActiveDirectoryDefault
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.globally_quoted_identifiers_skip_column_definitions=true

# Configuraci�n de JWT
jwt.secret=your-very-long-and-secure-secret-key-1234567890
jwt.expiration=3600